version: "3.3"
   
services:
  python-env:
    container_name: python-script
    build:
      context: .
      dockerfile: Dockerfile_Dev
    command: python tableau-ca.py
    volumes:
      - .:/code
